### ISSUE TITLE
Add CRUD operations with immutable.js and RxJS with simple api

### ISSUE THREAD

**Issue by lipenco** [philpl/react-fluorine-boilerplate#2]

**Comment by philpl** [comment]
This is hopefully gonna get rid of all the woes connected to CRUD soon: https://github.com/philpl/fluorine-orchestra

Orchestra will have boilerplate stores that abstract keeping offline collections as `OrderedMaps<Map>` and will:

- Resolve dependencies automatically
- Report missing ids in its stores
- Provide pre- and post-hooks for easy deserialization
- Provide boilerplate actions as methods on the stores

Its examples will most likely include a RESTful example that has some data structure that needs to be resolved dynamically. Let's see.

For now it's missing some unit tests and actual tests ;)
